sudo: required

language: bash

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.7.0
    - DOCKER_VERSION=1.10.1-0~trusty
    - IMAGE_NAME=bzon/jboss-liferay:6.2-ee-sp12

before_install:
 - apt-cache madison docker-engine
 - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
 - sudo rm /usr/local/bin/docker-compose
 - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
 - cd resources/installers && wget -q ${LIFERAY_DEPENDENCY} && cd -
 - cd resources/installers && wget -q ${LIFERAY} && cd -
 - cd resources/installers && wget -q ${MYSQL} && cd -
 - cd resources/installers && wget -q ${TOMCAT_JULI} && cd -
 - cd resources/installers && wget -q ${OJDBC6} && cd -
 - cd resources/installers && wget -q ${OJDBC7} && cd - 
 - docker build -t ${IMAGE_NAME} .
 - cd compose-for-mysql
 - docker-compose up -d
 - count=0; until [[ $(curl -I -s localhost:8080/liferay | grep 302 | wc -l) -eq 1 ]]; do echo "sleep 5 - count $count"; sleep 1; ((count ++)); if [[ $count -eq 30 ]]; then exit 1; fi; done

after_success:
 - if [ "$TRAVIS_BRANCH" == "master" ]; then
   docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
   docker push $IMAGE_NAME
   fi
 
